name: node-server-alpine:1.0

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: docker build -t ghcr.io/k1ver/node-server-alpine:1.0 .
      - name: pushing
        run: docker push ghcr.io/k1ver/node-server-alpine:1.0
      - name: check_success
        if: success()
        uses: K1ver/docker@main
        
      - name: check_failure 
        if: failure()
      
